### ISSUE TITLE
How do you handle synchronisation

### ISSUE THREAD

**Issue by AyiStar** [longhl104/COMP2017-assignment#1]
Hi, I'm not a student in Sydney University, but I'm trying your assignment.
I read your code for reference, I just wanna know how do you handle synchronisation?

**Comment by longhl104** [comment]
> Hi, I'm not a student in Sydney University, but I'm trying your assignment.
> I read your code for reference, I just wanna know how do you handle synchronisation?

I put the full version of my assignment. You can open fuse.c to have a look

**Comment by AyiStar** [comment]
Yeah, you have done this project well ^^
